version: "3.8"
services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app/backend
    ports:
      - "5100:8000"
    stdin_open: true
    tty: true
    environment:
      - DJANGO_SETTINGS_MODULE=backend.settings
    command: python3 manage.py runserver 0.0.0.0:8000
    restart: always

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      # One-way volume to use node_modules from inside image
      - /app/node_modules
    ports:
      - "80:3000"
    environment:
      - NODE_ENV=development
    depends_on:
      - backend
    command: npm start
    restart: always
